# Generated by Django 2.2.20 on 2021-04-17 06:43
import django
from django.db import migrations
django.setup()
from users.models import User


def create_default_super_admin(apps, schema_editor):
    User.objects.create_superuser('admin@example.com', 'admin1234')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_super_admin)
    ]
