"""
Django settings for prepare_be project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "-----BEGIN RSA PRIVATE KEY-----\nMIICWwIBAAKBgFbKy/72cEpDDXOvkQIIMii53b/71zo0Ct03O4QaSht4PpoFobF0\n3lShkY3/zGWtRPxwvVB/FDv8tAlQ0KuMDJvX3S7N3Xbnv9sMfUDyBf23/9A7o9JC\n4aKzWWBE+CVTktaswnkVRFWn+DAihSqs7Cl3pQzYMb82qRVJDAehCeppAgMBAAEC\ngYA4xAsIh0aKS7DQqVO+cH3eBTL0DlOGzeMNLMLQdCFkNhE7y9Mlrbp8v+/jYBrf\npaQpN9OagoNJeM6ICUNx7/eOcdKjB17tbUjaiDVLC9SBdC8atIwFhREo+I9C+PSq\nZg5O/qLy/at7oN9f2fZ1KxIgmnI9ziii5faKYmwBzAcYwQJBAKmlXLQyxA61pSja\nNkDLjj/0Rq+06tcsPGJWx96bGNzNTDsYBZWHFZ1zhragFMBdQDcowNlmdfgkZgBf\noqC2lZ8CQQCC+LkyBbyeCwYalXP9lPHzBmJAHZJeGXXuDvLwlyDA996mHZbBln5d\n3+pYXQQkISQKYfgXyrTZ1tzPwRr9ybL3AkBMuDHSdFrh5BfK/9QlPWkZVxlYgNLr\neF/egSxmaXG2+UkOOHDeDHcj+4jiskZwMDvINi/woTuceql+ZcGgOLI1AkAR2ZxD\n+Qwv7giy7tOUKAyhtqkFXAJq2MV94IOzzqUkJ6Qst7OoRr6KRM5HpMW/ttSWpauO\nco4bcnE9z2/CTw8ZAkEAml268J8MB0ytUddx9QoSiRhO18DixuOYvTx4PMHP8bQ/\nbder0bdRkl8wvgp+uuGTBg+eSqJPf7JRtUmcdKY/wA==\n-----END RSA PRIVATE KEY-----"

VERIFY_KEY = "-----BEGIN PUBLIC KEY-----\nMIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFbKy/72cEpDDXOvkQIIMii53b/7\n1zo0Ct03O4QaSht4PpoFobF03lShkY3/zGWtRPxwvVB/FDv8tAlQ0KuMDJvX3S7N\n3Xbnv9sMfUDyBf23/9A7o9JC4aKzWWBE+CVTktaswnkVRFWn+DAihSqs7Cl3pQzY\nMb82qRVJDAehCeppAgMBAAE=\n-----END PUBLIC KEY-----"


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',

    # 3rd parties
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',

    # own
    'users',
    'locations',
    'sales',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'build'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
REACT_APP_DIR = os.path.join(BASE_DIR, "src/frontend")
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(REACT_APP_DIR, "build", "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'build', 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
django_heroku.settings(locals())
AUTH_USER_MODEL = "users.User"
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'RS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': VERIFY_KEY,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(days=365),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=365),
}
