# Generated by Django 2.2.20 on 2021-04-17 06:43

from django.conf import settings
from django.db import migrations
import django, os, csv

django.setup()
from users.models import User

BASE_DIR = settings.BASE_DIR
csv_file_path = os.path.join(BASE_DIR, 'fixtures/sale_orders.csv')


def group_csv_data_by_email(reader):
    results = {}
    for date, product, sales_number, revenue, email in reader:
        results.setdefault(email, []).append(
            (date, product, sales_number, revenue)
        )
    return results


def import_csv(apps, schema_editor):
    with open(csv_file_path) as csv_file:
        reader = csv.reader(csv_file, delimiter=',')
        next(reader)  # ignore first row
        grouped_results = group_csv_data_by_email(reader)
        for email, rows_data in grouped_results.items():
            user, created = User.objects.get_or_create(
                email=email
            )
            if created:
                user.set_password('example123')
                user.save()
            user.create_sale_order_from_rows(rows_data)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20210417_0643'),
    ]

    operations = [
        migrations.RunPython(import_csv),
    ]
